# Generated by Django 5.2.7 on 2025-10-04 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatPlanetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koi_periode', models.FloatField(verbose_name='Période Orbitale (jours)')),
                ('koi_duration', models.FloatField(verbose_name='Durée du Transit (heures)')),
                ('koi_depth', models.FloatField(verbose_name='Profondeur du Transit (ppm)')),
                ('koi_impact', models.FloatField(blank=True, null=True, verbose_name="Paramètre d'impact (masse terrestre)")),
                ('koi_teff', models.FloatField(verbose_name='Température effective (K)')),
                ('koi_slogg', models.FloatField(verbose_name='Log de la gravité de surface (cgs)')),
                ('koi_srad', models.FloatField(blank=True, null=True, verbose_name='Rayon (rayons solaires)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
