# Generated by Django 5.2.7 on 2025-10-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatplanetaire',
            options={'verbose_name': 'Candidat Planétaire', 'verbose_name_plural': 'Candidats Planétaires'},
        ),
        migrations.AddField(
            model_name='candidatplanetaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatplanetaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
