# Generated by Django 5.2.7 on 2025-10-05 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_alter_candidatplanetaire_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatplanetaire',
            old_name='koi_periode',
            new_name='koi_period',
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_exoplanet', models.BooleanField(verbose_name='Est une exoplanète')),
                ('confidence', models.FloatField(verbose_name='Confiance de la prédiction (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='detector.candidatplanetaire')),
            ],
            options={
                'verbose_name': 'Prédiction',
                'verbose_name_plural': 'Prédictions',
            },
        ),
    ]
